enum Prefecture: Int {
    case hokkaido = 1
    case aomori = 2
    case iwate = 3
    case miyagi = 4
    case akita = 5
    case yamagata = 6
    case fukushima = 7
    case ibaraki = 8
    case tochigi = 9
    case gunma = 10
    case saitama = 11
    case chiba = 12
    case tokyo = 13
    case kanagawa = 14
    case niigata = 15
    case toyama = 16
    case ishikawa = 17
    case fukui = 18
    case yamanashi = 19
    case nagano = 20
    case gifu = 21
    case shizuoka = 22
    case aichi = 23
    case mie = 24
    case shiga = 25
    case kyoto = 26
    case osaka = 27
    case hyogo = 28
    case nara = 29
    case wakayama = 30
    case tottori = 31
    case shimane = 32
    case okayama = 33
    case hiroshima = 34
    case yamaguchi = 35
    case tokushima = 36
    case kagawa = 37
    case ehime = 38
    case kochi = 39
    case fukuoka = 40
    case saga = 41
    case nagasaki = 42
    case kumamoto = 43
    case oita = 44
    case miyazaki = 45
    case kagoshima = 46
    case okinawa = 47

    var description: String {
        switch self {
        case .hokkaido: return "北海道"
        case .aomori: return "青森県"
        case .iwate: return "岩手県"
        case .miyagi: return "宮城県"
        case .akita: return "秋田県"
        case .yamagata: return "山形県"
        case .fukushima: return "福島県"
        case .ibaraki: return "茨城県"
        case .tochigi: return "栃木県"
        case .gunma: return "群馬県"
        case .saitama: return "埼玉県"
        case .chiba: return "千葉県"
        case .tokyo: return "東京都"
        case .kanagawa: return "神奈川県"
        case .niigata: return "新潟県"
        case .toyama: return "富山県"
        case .ishikawa: return "石川県"
        case .fukui: return "福井県"
        case .yamanashi: return "山梨県"
        case .nagano: return "長野県"
        case .gifu: return "岐阜県"
        case .shizuoka: return "静岡県"
        case .aichi: return "愛知県"
        case .mie: return "三重県"
        case .shiga: return "滋賀県"
        case .kyoto: return "京都府"
        case .osaka: return "大阪府"
        case .hyogo: return "兵庫県"
        case .nara: return "奈良県"
        case .wakayama: return "和歌山県"
        case .tottori: return "鳥取県"
        case .shimane: return "島根県"
        case .okayama: return "岡山県"
        case .hiroshima: return "広島県"
        case .yamaguchi: return "山口県"
        case .tokushima: return "徳島県"
        case .kagawa: return "香川県"
        case .ehime: return "愛媛県"
        case .kochi: return "高知県"
        case .fukuoka: return "福岡県"
        case .saga: return "佐賀県"
        case .nagasaki: return "長崎県"
        case .kumamoto: return "熊本県"
        case .oita: return "大分県"
        case .miyazaki: return "宮崎県"
        case .kagoshima: return "鹿児島県"
        case .okinawa: return "沖縄県"
        }
    }
}
